### ISSUE TITLE
multiple fields with one request

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-profile-server#108]
We currently limit which fields third-party reliers can access, so they cannot use the open ended `profile` scope to get all fields in one request. They have to send separate requests for each field they want access to. It would be nice we supported returning multiple fields from a single request for scopes that the relier does have permission to use.

**Comment by rfk** [comment]
Note that we need this to go live simultaneously with https://github.com/mozilla/fxa-oauth-server/issues/243
