### ISSUE TITLE
Add etag to profile image endpoint

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-profile-server#111]
This will allow clients to know if the image has changed since they last requested it.

**Comment by zaach** [comment]
For reference, here's how the etag for displayName is set: https://github.com/mozilla/fxa-profile-server/blob/master/lib/routes/display_name/get.js#L34

**Comment by seanmonstar** [comment]
Oh nice. The etag for image could be the image id, since that changes if it's a new image, and it is a hex value. Or we could checksum it, but it just seems like wasted cycles to do that, unless I'm missing something.

**Comment by zaach** [comment]
Image ID should work fine. :+1:

**Comment by zaach** [comment]
closed by #114
