### ISSUE TITLE
Replace JSHint with ESLint

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-profile-server#118]
Heck, we're doing it in other repos (fxa-content-server, fxa-js-client).
Maybe switch to ESLint for all the repos so we can use a shared config.

**Comment by pdehaan** [comment]
Ref: #117

**Comment by seanmonstar** [comment]
Why the change?

**Comment by pdehaan** [comment]
JSHint isn't super active. I like ESLint better. And I got 2 people to agree with me in https://github.com/mozilla/fxa-content-server/issues/2550.

Plus, ESLint is more configurable so we can share configs, write custom rules, inherit settings from parent dirs, and is just basically pretty sweet.

You can say "No" and close this and I promise I won't be offended.

**Comment by seanmonstar** [comment]
"Yes."
