### ISSUE TITLE
GET /profile internal server error

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-profile-server#121]
Looks like there's an error while performing the batch request and it somehow cascades, causing a validation error to be triggered:

```
profile-server PORT 1111-8 (out): fxa-profile-server.server.ERROR: summary {"code":500,"method":"get","errno":999,"path":"/v1/profile","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36","t":30,"stack":"Error: code is not allowed. errno is not allowed. error is not allowed. message is not allowed. info is not allowed\n    at Object.exports.create (/Users/zcarter/moz/fxa-local-dev/fxa-profile-server/node_modules/hapi/node_modules/boom/lib/index.js:21:17)\n    at Object.exports.internal (/Users/zcarter/moz/fxa-local-dev/fxa-profile-server/node_modules/hapi/node_modules/boom/lib/index.js:246:92)\n    at Object.exports.badImplementation (/Users/zcarter/moz/fxa-local-dev/fxa-profile-server/node_modules/hapi/node_modules/boom/lib/index.js:282:23)\n    at postValidate (/Users/zcarter/moz/fxa-local-dev/fxa-profile-server/node_modules/hapi/lib/validation.js:150:26)\n    at internals.Any._validateWithOptions (/Users/zcarter/moz/fxa-local-dev/fxa-profile-server/node_modules/joi/lib/any.js:430:16)\n    at root.validate (/Users/zcarter/moz/fxa-local-dev/fxa-profile-server/node_modules/joi/lib/index.js:102:23)\n    at exports.response (/Users/zcarter/moz/fxa-local-dev/fxa-profile-server/node_modules/hapi/lib/validation.js:159:16)\n    at /Users/zcarter/moz/fxa-local-dev/fxa-profile-server/node_modules/hapi/lib/request.js:304:13\n    at iterate (/Users/zcarter/moz/fxa-local-dev/fxa-profile-server/node_modules/hapi/node_modules/items/lib/index.js:35:13)\n    at done (/Users/zcarter/moz/fxa-local-dev/fxa-profile-server/node_modules/hapi/node_modules/items/lib/index.js:27:25)"}
```

/cc @seanmonstar

**Comment by zaach** [comment]
This was caused by the access token not having an `email` field associated with it, so the get `email` batch request failed first. It appears the oauth-server doesn't return that field for the `profile:write` scope: https://github.com/mozilla/fxa-oauth-server/blob/master/lib/token.js#L23-L25

We can fix this in the content-server by adding the `profile` scope, though I assumed `profile:write` implied that scope. ¯\_(ツ)_/¯

**Comment by zaach** [comment]
Still, I'll leave this open so that we can improve error handling on the batch request used in the `/profile` endpoint.

**Comment by rfk** [comment]
Sounds like a bug in oauth-server to me, "profile:write" should definitely imply "profile" which implies "profile:email".  It will probably be automagically fixed when the refresh-tokens PR lands, which includes a nice refactor of the scope-checking logic.

**Comment by zaach** [comment]
@seanmonstar I think the action here would be handle the internal error and return something defined with an errorno. There's a stack trace in the initial comment with more deets.

**Comment by rfk** [comment]
We should also add an explicit test that `profile:write` implies the various profile sub-scopes like `profile:email`, unless we already got one of those as part of the scope-handling refactor from @seanmonstar's refresh-tokens work.

**Comment by rfk** [comment]
> We should also add an explicit test that profile:write implies the various profile sub-scopes like profile:email

For completeness, note that we do indeed have such tests now in the oauth server, thanks to @seanmonstar's refactor of scope handling:

  https://github.com/mozilla/fxa-oauth-server/blob/549dae3aa65def737811d71df54fc171547ed876/test/scope.js#L56
