### ISSUE TITLE
Limit allowed characters in display-name field

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-profile-server#126]
We don't want to accidentally XSS ourselves like @pdehaan did over in https://github.com/mozilla/fxa-content-server/issues/2794.

We should limit the allows characters in display names to alphnumeric plus some sensible metachars.

**Comment by seanmonstar** [comment]
Alphanumeric forces our users to have English names. How about instead,
htmlescaping the names?

**Comment by rfk** [comment]
Unicode has an "alphanumeric" character class, but still, good point - htmlescape may be closer to what we want here.  /cc @zaach to comment on how this might interplay with the work on the frontend.

**Comment by shane-tomlinson** [comment]
> Unicode has an "alphanumeric" character class, but still, good point - htmlescape may be closer to what we want here. /cc @zaach to comment on how this might interplay with the work on the frontend.

I'd say escape those things. Users will want to have strange names, including ones with `<` or `>`. We have the technology to make those safe, we should use it and "allow users to be who they want to be." (stealing a line from mine @callahad's talk in Brussels several years ago).

**Comment by pdehaan** [comment]
> @shane-tomlinson: "allow users to be who they want to be."

In that case, should we revisit allowable email address chars?
Per [/lib/routes/validators.js:66](https://github.com/mozilla/fxa-auth-server/blob/3e7c594380570062f16555bd014bcc8ab3521247/lib/routes/validators.js#L66) that seems a bit limiting.

I think our "aggressive" RegEx will fail on a bunch (50%, apparently) of the valid email addresses listed on https://en.wikipedia.org/wiki/Email_address#Valid_email_addresses

| EMAIL ADDRESS | RESULT | 
|----|:----:|
| niceandsimple@example.com | ✓ |
| very.common@example.com | ✓ |
| a.little.lengthy.but.fine@dept.example.com | ✓ |
| disposable.style.email.with+symbol@example.com | ✓ |
| other.email-with-dash@example.com | ✓ |
| "much.more unusual"@example.com | ✗ |
| "very.unusual.@.unusual.com"@example.com | ✗ |
| "very.(),:;<>[]\".VERY.\"very@\\ \"very\".unusual"@strange.example.com | ✗ |
| admin@mailserver1 | ✓ |
| #!$%&'*+-/=?^_`{}\|~@example.org | ✓ |
| "()<>[]:,;@\\\"!#$%&'*+-/=?^_`{}\| ~.a"@example.org | ✗ |
| " "@example.org | ✗ |
| üñîçøðé@example.com | ✗ |
| üñîçøðé@üñîçøðé.com | ✗ |

**Summary:** 7/14 pass.

**Comment by callahad** [comment]
As a pragmatic middle ground, I like the HTML 5 spec's definition of a valid email address, at https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address

Regex included, pragmatic, and generally what browsers will use for `<input type="email"></input>` fields.

**Comment by rfk** [comment]
> In that case, should we revisit allowable email address chars?
> Per /lib/routes/validators.js:66 that seems a bit limiting.

FWIW, I copied that logic directly from the code inside firefox that determines whether something entered into a form field is a valid email address.  Previously there was a mis-match and things could be flagged as invalid in the UI but accepted by the server, and vice-versa.  Could be worth revisiting to see if things are still in sync.

**Comment by rfk** [comment]
Also, OWASP [1, A3] says:
"""
Tip: Do not store data HTML encoded in the database. This prevents new uses for the data, such as web services, RSS feeds, FTP batches, data warehousing, cloud computing, and so on.
"""

https://www.owasp.org/index.php/OWASP_Top_Ten_Cheat_Sheet

**Comment by rfk** [comment]
from @ryanfeeley: Are there any reasons why we should forbid names that look like email addresses? (i.e. obama@whitehouse.gov).

I guess part of the problem here is that we don't have a consistent story about what display-name is *for*.  Is it just for displaying in place of their email address when we want to refer to this user?  Or might it be used more like a username?  This is potentially not just about making the values "safe" w.r.t. XSS etc, but also about ensuring they're not confusing to reliers, or other users.

Things that IMO have no business being in a display-name field include:  linefeeds, zero-width spaces, control characters, invalid utf-8 byte sequences, private-use or otherwise reserved unicode characters of any kind.

> Users will want to have strange names

Whatever restrictions we put in place, we should log metrics about how often they trip people up.

**Comment by ckarlof** [comment]
> Tip: Do not store data HTML encoded in the database. 

Absolutely. Do not store escaped data in the DB. My less experienced self has been burned by this before. It is an absolute headache. The Android team will bite our head off of the minute they want to show it in native Android UI. 

Supporting @shane-tomlinson's POV, we should be as liberal as possible (ideally, any valid UTF-8 string that can be reasonably displayed), and escape it when it needs to be displayed in HTML. Limiting it to 255 chars or something also seems reasonable.

**Comment by shane-tomlinson** [comment]
> My less experienced self has been burned by this before.

I'll learn of of your and @rfk's experience and say my suggestion was ill informed. :+1:

**Comment by rfk** [comment]
ISTM the right next-steps here are to add some testcases for things we definitely want to except, and things we might not want to accept.
