### ISSUE TITLE
Image processing error in prod

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-profile-server#128]
![image](https://cloud.githubusercontent.com/assets/128755/8939743/46154578-3534-11e5-8432-af68a29681d9.png)

![image](https://cloud.githubusercontent.com/assets/128755/8939749/5510c69c-3534-11e5-89c1-4e2cd52e315d.png)

cc @jrgm @seanmonstar

**Comment by vladikoff** [comment]
Here is a .har for the session from Firefox https://www.dropbox.com/s/76f5dzdl0i90ah5/Archive%2015-07-28%2014-27-31.har?dl=0

![image](https://cloud.githubusercontent.com/assets/128755/8939946/527a3b38-3535-11e5-84a0-05ed93b5e8e7.png)

I made 3 requests to change my avatar, got this error twice.

**Comment by jrgm** [comment]
At Tue Jul 21 13:45:43Z, one of three profile servers started logging errors - `"msg":"cannot enqueue work: maximum expected work duration exceeded (13.371434649555262s)"`. I am going to restart that server.

**Comment by seanmonstar** [comment]
That's compute-cluster...

**Comment by jrgm** [comment]
Okay, restarted. Processing images fine now. Closing as "fixed". Will open a followup to figure out what the bug is here.
