### ISSUE TITLE
improve monitoring for profile server getting stuck.

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-profile-server#130]
Follow on from https://github.com/mozilla/fxa-profile-server/issues/128

>> At Tue Jul 21 13:45:43Z, one of three profile servers started logging errors - "msg":"cannot enqueue work: maximum expected work duration exceeded (13.371434649555262s)". I am going to restart that server.

The box was showing almost no cpu at the time. It's unclear why it was in this state.

**Comment by seanmonstar** [comment]
compute-cluster doesn't measure cpu time, it measures the time it took for previous jobs to complete, multiplies that time by the number of current jobs, and then predicts how long a new job would take from that. profile-server workers use CPU to run graphicsmagick, but then take additional time waiting on the network as the processed image is inserted into an S3 bucket.

**Comment by rfk** [comment]
@jrgm points out that this is also a gap in monitoring, this should have sent some sort of alert in production

**Comment by vladikoff** [comment]
todo move this to puppet config issues

**Comment by vladikoff** [comment]
Continued in https://github.com/mozilla-services/puppet-config/issues/1561

**Comment by rfk** [comment]
@seanmonstar @jrgm did we ever figure out the cause of this in the end, or did it just go away eventually?

**Comment by seanmonstar** [comment]
I haven't thought about it since.
