### ISSUE TITLE
Rate-limit avatar upload attempts using fxa-customs-server?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-profile-server#132]
Avatar uploads are a potentially expensive operation that we could profitably rate-limit by IP-address and/or email-address.  It may be possible to use fxa-customs-server for this without too much work.  @seanmonstar what do you think about the potential benefits vs potential implementation costs of doing so?

**Comment by seanmonstar** [comment]
I think :+1:.

**Comment by vladikoff** [comment]
@vladikoff and @jrgm to chat about this

**Comment by vladikoff** [comment]
Orlando!
