### ISSUE TITLE
run_dev.js requirers rimraf but it is not in package.json

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-profile-server#138]
Am I missing something? 
Script: https://github.com/mozilla/fxa-profile-server/blob/master/scripts/run_dev.js#L11

Package.json: https://github.com/mozilla/fxa-profile-server/blob/master/package.json

**Comment by seanmonstar** [comment]
Nope, I completely forgot about run_dev when I updated that package.json. I was just aggresively cleaning.
