### ISSUE TITLE
"avatar.get" activityEvent

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-profile-server#146]
Hey @rfk, we are looking at add `"avatar.used"` (name pending) activityEvent that would originate from the oauth / profile server and then calculate retention for users that have "avatar.used".  This might be an oauth server issue though. 

cc @philbooth

**Comment by vladikoff** [comment]
@rfk we want to add it sooner than later so we can start gathering data

**Comment by rfk** [comment]
This repo is probably the right place, adding it to one or more of the routes in https://github.com/mozilla/fxa-profile-server/tree/master/lib/routes/avatar
