### ISSUE TITLE
small number of avatar uploads rejected for >1MB size

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-profile-server#148]
STR

1. install `netpbm` to generate an uncompressible png (white noise)

2. `rawtoppm < /dev/urandom > rnd.ppm; pnmtopng < rnd.ppm > rnd.png`

3. try to upload `rnd.png` as your avatar

Expected: the server will return 'HTTP/1.1 413 Request Entity Too Large'; reflect that to the user in the UI

Actual: Fx network console doesn't show an HTTP response to the /v1/avatar/upload request; the UI shows 'System unavailable, try again soon'.

**Comment by edmoz** [comment]
jrgm to increase limit for investigation.

**Comment by zaach** [comment]
jrgm noted that the browser is not actually receiving the 413 error although nginx is sending it. The browser will need to see the 413 in order for us to give better messaging.

**Comment by seanmonstar** [comment]
I... what? 413 is being sent, but not the browser isn't receiving it? How can that be?

**Comment by jrgm** [comment]
I have a fix to raise the limit on nginx, but this will also need a change in fxa-profile-server.

The change needed is to add `maxBytes: 1200000` [here](https://github.com/mozilla/fxa-profile-server/blob/master/lib/server/worker.js#L48), and [here](https://github.com/mozilla/fxa-profile-server/blob/master/lib/routes/avatar/upload.js#L38).

However, in writing tests for this, it turns out the current tests `test/lib/mock.js` is tied to a specific image and size [here](https://github.com/mozilla/fxa-profile-server/blob/master/test/lib/mock.js#L136) and [here](https://github.com/mozilla/fxa-profile-server/blob/master/test/lib/mock.js#L45)

**Comment by seanmonstar** [comment]
This was assigned to me and put in now, but I don't see what the specific action is...

**Comment by seanmonstar** [comment]
Since this issue is larger than the specific action needed in 'now', I've created #158, which 'blocks' this. I'll move this into next, and fix #158.

**Comment by rfk** [comment]
Is there any further action required on this bug once #158 lands?  If not, I suggest we just close it out in favour of the more action-oriented one.

**Comment by seanmonstar** [comment]
@rfk it seems this issue is to find out why avatars are being rejected. so next steps are likely to increase the maxSize in production a little, and then monitor if the errors go away, etc.

**Comment by rfk** [comment]
IIUC the next action here is to confirm whether train-48 deployment helped the situation any

**Comment by jrgm** [comment]
this is fixed
