### ISSUE TITLE
Allow `DELETE /v1/avatar` with no id to delete the currently-selected avatar

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-profile-server#149]
The ID is needed to delete the image. It *is* returned by /avatar endpoints.

**Comment by rfk** [comment]
I'm not sure how to get around this in a backwards-compatible way; the profile endpoint currently returns just the avatar URL, so we can't change that to a `{ id, url }` hash without breaking older clients.

Deleting the image doesn't seem like a very common operation, do we need to optimize for this case, or can we just require clients to interact directly with the `/avatar` endoint if they need to do that?

**Comment by seanmonstar** [comment]
I agree that the profile endpoint probably shouldn't include all the
details of all the things.

However, since we don't currently use the ability to have multiple avatars,
use of the id is not really needed. It'd be a backwards compatible change
to allow a DELETE /v1/avatar with no id, which would delete the currently
"selected" avatar.

**Comment by zaach** [comment]
> It'd be a backwards compatible change
to allow a DELETE /v1/avatar with no id, which would delete the currently
"selected" avatar.

I like it. :+1:

**Comment by rfk** [comment]
(updated bug title to reflect the proposed solution)

**Comment by vladikoff** [comment]
@seanmonstar @rfk do we still want to do this?

**Comment by rfk** [comment]
I personally don't care strongly for this feature, unless we have a burning desired to use it in the calling code.  @seanmonstar?

**Comment by seanmonstar** [comment]
I don't care at all. My guess is that it was a wish for the Settings app to
be able to delete using only 1 request.
