### ISSUE TITLE
Add support for "locale" profile field

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-profile-server#156]
Once fxa-auth-server adds a /account/profile endpoint in https://github.com/mozilla/fxa-auth-server/issues/1053, we'll be able to use `profile`-scoped oauth tokens to read `email` and `locale` fields for a user.  We should add support for reading the locale as part of the profile data.

**Comment by vladikoff** [comment]
What milestone should this be part of @rfk ?

**Comment by rfk** [comment]
Let's just backlog this until a relier shows up needing it.

**Comment by vladikoff** [comment]
@rfk should we close this for now?

**Comment by rfk** [comment]
yes, good call
