### ISSUE TITLE
Allow only a single avatar per user

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-profile-server#160]
We currently allow users to upload multiple avatars, with the original idea of allowing them to switch between pictures on e.g. a relier by relier basis.  We haven't shipped that and we have no concrete plans to, so we're paying a complexity cost that doesn't give us any benefit.

Let's simplify our backend avatar support so that the user only has a single avatar, and uploading a new one deletes the old one.

Also as noted in https://github.com/mozilla/fxa-profile-server/issues/94, this will make cleanup of old avatar pictures easier, and will probably help clients with discovering that the avatar has changed.

**Comment by jstrutz** [comment]
@rfk I'm happy to take a crack at this, if it is still on the table?

**Comment by rfk** [comment]
Sure!  I don't think it should be *too* complicated a cleanup; @seanmonstar are you happy to provide a bit of mentorship here?

**Comment by seanmonstar** [comment]
Absolutely. Let me know if you need a breakdown, or if you feel comfortable just chopping, go right ahead.

**Comment by jstrutz** [comment]
Great!  I'd be happy to hear your breakdown @seanmonstar .  How far do we want to take the cleanup? - i.e. do we want to simplify the API?  Change the DB schema?

**Comment by seanmonstar** [comment]
- we can drop the [avatar_selected](https://github.com/mozilla/fxa-profile-server/blob/master/lib/db/mysql/schema.sql#L25) table
- remove the [selected](https://github.com/mozilla/fxa-profile-server/blob/master/lib/db/mysql/index.js#L154) argument to `db.addAvatar`
- remove the [getSelectedAvatar and getAvatars](https://github.com/mozilla/fxa-profile-server/blob/master/lib/db/mysql/index.js#L177-L183) db methods
- Mirror those chops with the memory db
- remove the [selected](https://github.com/mozilla/fxa-profile-server/blob/master/lib/routes/avatar/post.js#L32) parameter from the `POST` route (probably just make it optional for now and don't check it in the handler)
- The `routes/list.js` should just get the axe.

**Comment by rfk** [comment]
> we can drop the avatar_selected table

Also to flag, this sounds like the sort of thing that's going to require at least two deployments to do in a rollback-compatible way, i.e. we can only actually drop it *after* there's no more code using it running in production.

**Comment by vladikoff** [comment]
I looked it at this while cleaning up https://github.com/mozilla/fxa-profile-server/pull/279 and the migrations are looking pretty annoying plus we have a lot of other migrations going on. Please reopen if we still think we really need this.
