### ISSUE TITLE
Fetch the email from the auth-server instead of the oauth server

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-profile-server#165]

**Comment by rfk** [comment]
The fix from #166 seems to be failing if you hit the top-level "profile" endpoint rather than asking for just the email address.  The `req.auth` bundle in that case contains:

```
{
  "isAuthenticated":true,
  "credentials": 
      {
        "user":"52c28dde953e41c997bf21dfe961c9f0",
        "client_id":"98e6508e88680e1a",
        "scope":["profile","profile:write"]
      },
  "session":null,
  "mode":"required",
  "strategy":"bypass"
}
```

Which doesn't include the oauth token, so we can't pass it on to the auth-server endpoint.
