### ISSUE TITLE
check if we can add user agent to activity events

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-profile-server#183]

**Comment by rfk** [comment]
We could, but it's not obvious how often we'd get the UA of the user's browser vs the UA of whatever relier is fetching the profile data.  We might be able to do something clever like check the owner of the oauth token, and if it's e.g. issued to Firefox directly when we know that the UA is the user's actual UA.

**Comment by shane-tomlinson** [comment]
@seanmonstar, @rfk, @vladikoff - can one of you triage this as appropriate?

**Comment by vladikoff** [comment]
useful consumer of avatars (such as Firefox Desktop) won't have user agent when fetching. not needed for now.
