### ISSUE TITLE
MySQL truncates display-names with astral-plane unicode characters

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-profile-server#186]
Originally from https://github.com/mozilla/fxa-content-server/issues/3208

"So that I can express myself more uniquely and humorously, as an account holder user, I want to be able to use emojis in my display name on the web and in Firefox."

"✨☕️✨ works, but everything after 🚲 gets cut off for no apparent reason…"

As far as I can tell profile-server is silently truncating the display-name after the unicode character, e.g.:

```
>>> requests.post("https://profile.accounts.firefox.com/v1/display_name", u"{\"displayName\": \"rfkelly \U0001F6B2 sparkle\"}".encode("utf8"), headers={"Authorization": AUTHZ})
<Response [200]>
>>> requests.get("https://profile.accounts.firefox.com/v1/display_name", headers={"Authorization": AUTHZ}).content
'{"displayName":"rfkelly "}'
```

Strangely I cannot reproduce this in the profile-server test suite itself, adding unicode bicycle into the test suite works fine.

**Comment by rfk** [comment]
The reported etag is "014031c66bd06bb5d0ba9f0e85d60bf50393b034" which is the checksum of the truncated form "rfkelly ", so perhaps this is happening in the db rather than the server code.

**Comment by rfk** [comment]
Yep, running a local test against mysql rather than the in-memory db gives me this:

```
,"stack":"Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\\xF0\\x9F\\x9A\\xB2  ...' for column 'displayName' at row 1
```

**Comment by rfk** [comment]
Ref https://github.com/felixge/node-mysql/issues/839

**Comment by rfk** [comment]
So I guess our mysql is silently truncating the value in production.

**Comment by rfk** [comment]
Also ref https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-utf8mb4.html

**Comment by rfk** [comment]
I feel like we should, at the very least, error out here rather than truncating the input, which probably means tweaking something in the mysql config.  @jrgm thoughts?

**Comment by vladikoff** [comment]
> I feel like we should, at the very least, error out here rather than truncating the input, which probably means tweaking something in the mysql config. @jrgm thoughts?

Is there a way to address this by doing a migration on the table with the stored display names?

**Comment by rfk** [comment]
> we should, at the very least, error out here rather than truncating the input

FWIW, we do now error out in these cases, be rejecting the data at the application layer.

One of the holdups on this work more broadly has been stored procedures - stored procedures remember the string collation settings, sql mode, etc that were in place when they were created.  But I just realized that this repo doesn't use stored procedures!  So we don't have to block on that here.  We should:

* Find a way to ensure the db is always running with strict mode on.
* Work on a db migration to convert the displayName column to utf8.
* Once we're happy with it, re-enable submitting emojis etc through the API.

**Comment by shane-tomlinson** [comment]
@rfk - is this still worthy of being in next? Seems like it's been here a while.

**Comment by rfk** [comment]
Let's bump it out

**Comment by vladikoff** [comment]
We have the technology, fixed in https://github.com/mozilla/fxa-profile-server/pull/248

![image](https://cloud.githubusercontent.com/assets/128755/26807756/568ed78a-4a26-11e7-825a-86310b0179d4.png)
