### ISSUE TITLE
Implement contextual identity

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-profile-server#19]
This is support for multiple profiles and the choice of where to use each of them. Background reading: http://w2spconf.com/2013/papers/s1p2.pdf

This is longer term, but high impact stuff, and I'd like to encourage experimentation now.

/cc @ryanfeeley

**Comment by rfk** [comment]
@ckarlof @ryanfeeley if you're still keen on doing this, y'all can bring it up in a product planning meeting and we'll get it captured in Aha.  Closing out here.
