### ISSUE TITLE
display name length error

### ISSUE THREAD

**Issue by udaraweerasinghege** [mozilla/fxa-profile-server#261]
If you create a display name that is very long (not sure what allowed length is), it will save successfully, however if you refresh the page, the following error can be seen in profile server:

```fxa-profile-server.server.ERROR: summary {"code":500,"method":"get","errno":999,"path":"/v1/profile","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Firefox/54.0","t":10,"remoteAddressChain":["127.0.0.1"],"client_id":"98e6508e88680e1a","stack":"Error: child \"displayName\" fails because [\"displayName\" must be a string]\n    at postValidate (/Users/uweerasinghege/Mozilla/fxa-local-dev/fxa-profile-server/node_modules/hapi/lib/validation.js:201:26)\n    at _validateWithOptions (/Users/uweerasinghege/Mozilla/fxa-local-dev/fxa-profile-server/node_modules/joi/lib/any.js:604:20)\n    at root.validate (/Users/uweerasinghege/Mozilla/fxa-local-dev/fxa-profile-server/node_modules/joi/lib/index.js:105:23)\n    at internals.input.exports.response.postValidate (/Users/uweerasinghege/Mozilla/fxa-local-dev/fxa-profile-server/node_modules/hapi/lib/validation.js:221:20)\n    at each (/Users/uweerasinghege/Mozilla/fxa-local-dev/fxa-profile-server/node_modules/hapi/lib/request.js:384:16)\n    at iterate (/Users/uweerasinghege/Mozilla/fxa-local-dev/fxa-profile-server/node_modules/hapi/node_modules/items/lib/index.js:36:13)\n    at done (/Users/uweerasinghege/Mozilla/fxa-local-dev/fxa-profile-server/node_modules/hapi/node_modules/items/lib/index.js:28:25)\n    at finalize (/Users/uweerasinghege/Mozilla/fxa-local-dev/fxa-profile-server/node_modules/hapi/lib/handler.js:21:16)\n    at /Users/uweerasinghege/Mozilla/fxa-local-dev/fxa-profile-server/node_modules/hapi/lib/protect.js:52:16\n    at wrapped (/Users/uweerasinghege/Mozilla/fxa-local-dev/fxa-profile-server/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)\n    at finalize (/Users/uweerasinghege/Mozilla/fxa-local-dev/fxa-profile-server/node_modules/hapi/lib/handler.js:86:16)\n    at wrapped (/Users/uweerasinghege/Mozilla/fxa-local-dev/fxa-profile-server/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)\n    at internals.Response._prepare.internals.Response._processPrepare.next [as _processPrepare] (/Users/uweerasinghege/Mozilla/fxa-local-dev/fxa-profile-server/node_modules/hapi/lib/response.js:521:16)\n    at internals.Response._prepare.next [as _prepare] (/Users/uweerasinghege/Mozilla/fxa-local-dev/fxa-profile-server/node_modules/hapi/lib/response.js:460:21)\n    at /Users/uweerasinghege/Mozilla/fxa-local-dev/fxa-profile-server/node_modules/hapi/lib/reply.js:152:22\n    at nextTickCallbackWith0Args (node.js:489:9)"}```

**Comment by vladikoff** [comment]
@rfk does it make sense to add extra validation to the /display_name route to be max 256 characters? It seems it is having trouble with 256+ chars

**Comment by rfk** [comment]
Nice catch, we should definitely limit this.  It looks like the `GET` route restricts it to 256 characters:

  https://github.com/mozilla/fxa-profile-server/blob/master/lib/routes/display_name/get.js#L17

But the `POST` route where you set the name, doesn't apply this limit:

  https://github.com/mozilla/fxa-profile-server/blob/master/lib/routes/display_name/post.js#L32

Adding the same limit in the `POST` route sounds 👍.

**Comment by vladikoff** [comment]
@udaraweerasinghege Could you take a look at this one? Should be a simple PR ( I hope ! )
