### ISSUE TITLE
catbox timeout exceptions talking to redis

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-profile-server#273]
We have production errors at a small but consistent level:
```
"stack":"Error: Service Unavailable
    at null._onTimeout (/app/node_modules/hapi/node_modules/catbox/lib/policy.js:139:43)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by vladikoff** [comment]
Should be fixed via https://github.com/mozilla/fxa-profile-server/commit/7b5ed1b53d106ee0e4c5c31348d44546b94df16e

**Comment by vladikoff** [comment]
Also to clarify, in this case it was "catbox timeout exceptions talking to **database**, not redis"
