### ISSUE TITLE
Subscriptions API to notify relying parties of changes to user data

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-profile-server#28]
Generally, it might be a good alternative to relier polling and allow reliers to cache (slow changing) user data. 

I think this would also help address ownership changes of phone numbers if/when we allow them to be added to profile data.

Here's an example of a subscriptions API: https://wiki.fitbit.com/display/API/Fitbit+Subscriptions+API#FitbitSubscriptionsAPI-receivingUpdateNotifications

**Comment by rfk** [comment]
This will be covered by https://github.com/mozilla/fxa-notification-server, I don't think there's more we can flesh out in this bug in isolation
