### ISSUE TITLE
Fix nsp #534

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-profile-server#287]
Ref:

```
 debug   2.2.0       >= 2.6.9 < 3.0.0 || >= 3.1.0   fxa-profile-server@1.96.0 > gm@1.22.0 > debug@2.2.0   https://nodesecurity.io/advisories/534 
```

Tried to update modules but tests failing: 

https://github.com/mozilla/fxa-profile-server/pull/285#discussion_r142488476

**Comment by rfk** [comment]
> Tried to update modules but tests failing:

FWIW I took your PR and did `s/require('gm')/require('gm-reloaded')/g` on the code and that seemed to fix the tests, see #289
