### ISSUE TITLE
Cache clearing can race with other reliers handing `primaryEmailChanged` event

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-profile-server#288]
When a user changes their primary email address, we notified various interested parties by sending a `primaryEmailChanged` event, either via SQS or via WebChannel.  If those parties happen to receive and act on the event before the profile-server does, they can observe stale profile data from our cache.

Consider for example:

* A user changes their primary email; we send a WebChannel message to the browser and an SQS message to profile-server
* The browser receives the WebChannel message and tries to fetch the updated profile info before profile-server has received the SQS message
* The browser will read stale data from our cache, including the old primary email address

Or for example:

* A user changes their primary email; we send an SQS message to profile-server and to basket
* Basket receives the notification first.  To ensure it's not receiving a stale message [1] it asks profile-server for the user's latest profile information
* Basket will read stale data from our cache, including the old primary email address

I'm not entirely sure what our options are, but it'd be great to figure out a way to avoid potential races between the profile cache here and other reliers...

Options might include:

* Having the auth-server just reach into redis and clear the cache data used by profile-server;  I don't really like this from a separation-of-concerns perspective but it would certainly work.
* Having the auth-server message the profile-server, and then having profile-server send the messages out to other reliers once it's updated its own internal state.
* Smushing auth-server, profile-server and oauth-server together into a single service and avoiding these issues entirely :grin:

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1384385#c6

**Comment by vbudhram** [comment]
from mtg: not a concern now, closing
