### ISSUE TITLE
compute.image-cc.time.ms.gm.small event isn't compatible with mozlog

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa-profile-server#292]
```
{"EnvVersion":"2.0","Severity":6,"Timestamp":"2017-11-03 14:09:12","Pid":5,"Fields":{"msg":"spawned new worker process (11) 1/5 processes running"},"Logger":"fxa-profile-server","Type":"compute.image-cc"}
{"EnvVersion":"2.0","Severity":6,"Timestamp":"2017-11-03 14:09:19","Pid":11,"Fields":{"msg":1649},"Logger":"fxa-profile-server","Type":"compute.image-cc.time.ms.gm.small"}
```

`"msg":1649` isn't compatible mozlog, it needs to be a string. We should also make sure the other resize events don't print a number

**Comment by shane-tomlinson** [comment]
Hey @vladikoff - do you know anything about this? @jbuck says it's important.

**Comment by rfk** [comment]
In https://github.com/mozilla/mozlog/pull/18 I add a coercion to ensure we output valid mozlog, but we should really fix this particular log line to emit fields in a json struct rather than a plain integer.  Patch incoming.
