### ISSUE TITLE
bin/server prints mysql cleartext password on startup

### ISSUE THREAD

**Issue by nthuemmel** [mozilla/fxa-profile-server#297]
When starting the server, for instance by using `NODE_ENV=development node bin/server.js`, an INFO message is printed containing the entire `config`, including the cleartext password for the mysql database, both in development and production environments. As this could easily end up in log files, it would probably be best to remove this confidential information from the output.

**Comment by jrgm** [comment]
Thanks. You're right. Bad practice. Fix in #298 (other repos to eventually follow).
