### ISSUE TITLE
Should we crop avatar images to a circle?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-profile-server#299]
Spinning this off from https://github.com/mozilla-lockbox/lockbox-extension/pull/486#issuecomment-360642810 for discussion.

We display avatar images with a circular crop in our own web content.  When Lockbox added avatar support, they assumed the images themselves would be cropped to a circle, and were surprised to have to add the circle styling on their side.

As I'm writing this, I checked my avatar display in the Firefox hamburger menu, and it's not circular:
  
<img width="199" alt="capture" src="https://user-images.githubusercontent.com/34695/35488936-0d065434-04e4-11e8-8cbf-15d546f0e1f9.PNG">

Do we expect these images to always be displayed in the same circular style as we use them ourselves, and if so, should we crop the images to enforce this?  /cc @ryanfeeley.

**Comment by ryanfeeley** [comment]
We should not crop them.

I was surprised to see that the Photon team went with a square icon in the application menu, but I support the decision.

Cropping by default reduces our options in the future.

**Comment by rfk** [comment]
👍 that works for me, thanks for discussing :-)
