### ISSUE TITLE
Report account MFA status as part of profile info

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-profile-server#302]
For the IAM integration, they want to be able to query whether an account is MFA enabled. Github handles this by reporting a simple "two_factor_authentication": true|false field as part of the user's profile info, and we could do something similar here.

Depends on the auth-server exposing this data: mozilla/fxa-auth-server#2314

**Comment by rfk** [comment]
Concretely, we can report both a boolean yes/no as well as the list of available authentication methods, which would look something like:

```
{
  two_factor_authentication: true,
  amr_values: ["pwd", "otp"]
}
```

For symmetry with the proposal in https://github.com/mozilla/fxa-oauth-server/issues/519#issuecomment-367213438

**Comment by vladikoff** [comment]
👍
