### ISSUE TITLE
Enforce uid in the response schema for profile

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-profile-server#303]

**Comment by rfk** [comment]
From the report in slack:

"""
hihi! I have encountered an interesting FxA profile bug with one of my test accounts — when switching the scope on my auth token as requested from `oauth.accounts.firefox.com/v1/authorization` from `profile:email openid` to `profile openid`, the resulting `GET` to `profile.accounts.firefox.com` does not include my `uid`

the email associated with the account is `sasha+test@mozilla.com`
"""

**Comment by vladikoff** [comment]
Closing due to https://github.com/mozilla/fxa-profile-server/blob/9b3366652e678b5b50329f9b22b0f551b67490e8/test/api.js#L283
