### ISSUE TITLE
Clean up `Buffer` calls to deprecated API

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-profile-server#309]
![image](https://user-images.githubusercontent.com/128755/37316284-85d39ae0-2634-11e8-8e40-67a9f67b4208.png)

cc @deeptibaghel

**Comment by vladikoff** [comment]
Ref https://github.com/mozilla/fxa/issues/274

**Comment by deeptibaghel** [comment]
@vladikoff i will complete it.
