### ISSUE TITLE
profile endpoint's values aren't changed immediately (caching issue?)

### ISSUE THREAD

**Issue by gdestuynder** [mozilla/fxa-profile-server#313]
When querying the profile endpoint right after changing some of it's values, it still shows the old values.

*Example*
- create new FxA account
- add 2FA (eg. via https://latest.dev.lcip.org/settings/two_step_authentication?showTwoStepAuthentication)
- query profile endpoint for that FxA account:   https://latest.dev.lcip.org/profile/v1/profile

*Expected result*
```
{
...
amrValues=[..., "totp"],
twoFactorAuthentication=true
...
```

*Actual result*
```
{
...
amrValues=["pw", "mail"],
twoFactorAuthentication=false
...
```

If I wait a bit, eventually, the values returned become correct.

**Comment by vladikoff** [comment]
@gdestuynder there is a redis cache yes. It should be purged when profile updates happen. maybe the `twoFactorAuthentication` field change is not purging it?

**Comment by rfk** [comment]
> maybe the twoFactorAuthentication field change is not purging it?

This is almost certainly the case, we could add a new SQS event from auth-server to propagate this info over.

**Comment by vladikoff** [comment]
Here's an example of the drop https://github.com/mozilla/fxa-profile-server/blob/21ca175f8ece9fc719aecb09f80aaa807a0b5349/lib/routes/display_name/post.js#L37

💧
