### ISSUE TITLE
Relier library for FxA and attached APIs

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-profile-server#38]
It would nice to have a client JS library for our reliers to use on the front end.

**Comment by rfk** [comment]
@shane-tomlinson is this old bug covered by your work on fxa-relier-client?  Please close out if so.

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson is this old bug covered by your work on fxa-relier-client? Please close out if so.

For future issue spelunkers, visit https://github.com/mozilla/fxa-relier-client for the JavaScript FxA relier client.
