### ISSUE TITLE
[Discuss] Allow users to add more than 2 emails to their accounts

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-profile-server#388]
I know that we technically have the capability but our UX doesn't surface it.

Is there any other reason for us to not surface more than 2 emails?

**Comment by davismtl** [comment]
see also #387 and #361

**Comment by vladikoff** [comment]
see also https://github.com/mozilla/fxa-content-server/issues/6748

**Comment by shane-tomlinson** [comment]
Closing here, let's [re-open the content server issue](https://github.com/mozilla/fxa-content-server/issues/6748) that already has a lot of discussion from the end of Q4.
