### ISSUE TITLE
Input sanitization: Limits on size and intensiveness of output of GraphicsMagick

### ISSUE THREAD

**Issue by karlht** [mozilla/fxa-profile-server#57]
Reference: http://www.graphicsmagick.org/GraphicsMagick.html

Under the 'Environment' section of the above man page, we should consider setting most if not all of the `MAGICK_LIMIT_*` variables, so that e.g. a very small PostScript input doesn't wind up rasterizing to a multi-gigabyte output.

Other resource-limiting schemes may also be good to have; it would be good if one misbehaving conversion did not bring all other avatar uploading to a screeching halt, for instance.

Does anyone else have any other specific concerns around input/image validation/sanitization?

**Comment by shane-tomlinson** [comment]
From triage, at a minimum, we should restrict file size and file type.

**Comment by rfk** [comment]
Since we're now seeing lots more traffic on avatar endpoints, let's prioritize this
