### ISSUE TITLE
upload returns 201 despite worker failing to upload to S3

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-profile-server#75]
I was in a state in stage where S3 was not allowing uploads (permission error). 

However, the request to https://profile.stage.mozaws.net/v1/avatar/upload was returning 'HTTP 201 Created' despite the failure. (It seems to me we had an issue filed about this "optimistic" response behaviour, but I can't find one now).

**Comment by rfk** [comment]
We haven't seen this in a while, I going to optimistically close it out

**Comment by jrgm** [comment]
Actually, this is the same effectively as https://github.com/mozilla/fxa-profile-server/issues/96.
I think adding "headers['accept-encoding'] = 'identity'" to suppress gzipping to a localhost server is a good fix.

**Comment by rfk** [comment]
OK, I filed https://github.com/mozilla/fxa-profile-server/issues/98 to explicitly follow up on that
