### ISSUE TITLE
POST /avatar/upload should delete the user's previous avatar from S3

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-profile-server#94]
Alternately, [the client could delete it](https://github.com/mozilla/fxa-profile-server/pull/90#issuecomment-73764331), but that's less reliable and I think we'll end up with a bunch of orphaned images.

This also means we only support one image per account, but that's all our front UI allows right now anyway.

**Comment by rfk** [comment]
@seanmonstar IIUC we properly support multiple avatars and have little risk of leaving orphans, do you think we can just close this one out?

**Comment by seanmonstar** [comment]
@rfk we have little risk? I don't think the UI shows your multiple avatars. Looking at the routes `avatar/post.js` and `avatar/upload.js`, it seems the db has a new avatar added, and it's updated to the 'selected', but any previous avatar is likely left in place, lonely in the void.

**Comment by rfk** [comment]
I meant leaving orphans in the backend; we get multiple avatar records in the db which won't be used currently, but we don't wind up with randonly-generated filenames sitting alone in S3 with nothing pointing to them.  They'll all get deleted if e.g. the user deletes their account.

If the scope of this bug is "don't leave orphaned files sitting around in S3" then I think we're OK; if it's more about not accumulating invisible old avatars in the db then I agreeit's unfixed, but it seems like a larger piece of work.

**Comment by rfk** [comment]
> This also means we only support one image per account, but that's all our front UI
> allows right now anyway.

Thinking about it, I'm not convinced we'll ever get around do doing something with selecting between multiple avatars.  Perhaps we should morph this into a more general "only have one avatar" bug?

**Comment by ckarlof** [comment]
The lingering concern I had was around how clients detect the avatar has changed without continually checking with the profile server to see if it has. The image ever 404s, then it's is pretty clear we should refetch the profile URL. If they never 404 after an image change (e.g., because we don't delete the old one), I'm worried clients might continue to display an old profile image after an image change.

**Comment by rfk** [comment]
If we de-scope to just a single profile image, I think the "make it 404 by deleting the old one" behaviour you describe above is exactly the right thing to do.

**Comment by seanmonstar** [comment]
@rfk to create actions.

**Comment by rfk** [comment]
@rfk to re-file this as an action driven bug around not having multiple avatars

**Comment by rfk** [comment]
I filed https://github.com/mozilla/fxa-profile-server/issues/160 as a concrete "let's remove multiple avatars support" bug, closing this one out.
